const styles = ["Джаз", "Блюз"];
console.log(styles);
styles.push("Рок-н-ролл");
console.log(styles);
styles[Math.round(styles.length / 2) - 1] = "Классика";
console.log(styles);
styles.shift();
console.log(styles);
styles.unshift("Регги");
styles.unshift("Рэп");
console.log(styles);
